[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.12.1"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  revision = "9beb055b7962d16947a14e1cd718098a2431e20e"

[[constraint]]
  name = "github.com/wavefronthq/go-metrics-wavefront"
  version = "0.9.0"

[prune]
  go-tests = true
  unused-packages = true
