[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.12.1"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  name = "github.com/wavefronthq/go-metrics-wavefront"
  version = "0.9.0"

[prune]
  go-tests = true
  unused-packages = true
