name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEP_VERSION: "0.5.0"

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.9.x", "1.10.x", "1.11.x", "1.12.x", "1.13.x", "1.14.x", "1.15.x", "1.16.x", "1.17.x" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Setup Go
      run: |
        curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
        chmod +x $GOPATH/bin/dep

    - name: Install Dependencies
      run: go get -t -v ./...

    - name: Gofmt
      run: diff -u <(echo -n) <(gofmt -d .)

    - name: Test
      run: go test -v -race ./...

    - name: Vet
      run: go vet ./...
