name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEP_VERSION: "0.5.0"

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.9.x", "1.10.x" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install Dependencies
      run: go get -t -v ./...

    - name: Gofmt
      run: diff -u <(echo -n) <(gofmt -d .)

    - name: Test
      run: go test -v -race ./...

    - name: Vet
      run: go vet ./...
